### ISSUE TITLE
Make "Stock filter" selected by default 

### ISSUE THREAD

**Issue by ia-gaurav** [nordcomputer/magento2-stockfilter#6]
i want to make "exclude out of stock" to be selected by default. i there way to do for it

**Comment by nordcomputer** [comment]
Sorry, not with this extension - as it would involve way more work than I am willing to invest - it would need to involve the cache and some other logics. Since I am not using this extension and only programmed it as it was a community request, it would be nice, if someone else would jump in to help you.
